# Generated by Django 5.2.13 on 2026-06-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_products_created_by_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('pcs', 'pcs'), ('dozen', 'dozen'), ('trays', 'trays'), ('litres', 'litres')], default='pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
